FoodTruck.delete_all
User.delete_all
Review.delete_all
Vote.delete_all

profile_photos = Dir.entries("#{Rails.root}/profile_images")

profile_photos.each do |photo|
  profile_photos.reject! { |photo| photo[-3..-1] != "jpg" && photo[-3..-1] != "png" }
end

profile_photos.size.times do |i|
  User.create({
    first_name: Randgen.first_name(length: rand(7) + 4),
    last_name: Randgen.last_name(length: rand(7) + 4),
    email: "seed#{i+1}@seeds.com",
    password: "seeder123",
    password_confirmation: "seeder123"
  })
end

User.all.each_with_index do |user, i|
  user.profile_photo.store!(File.open(File.join(Rails.root, "/profile_images/#{profile_photos[i]}")))
  user.save!
end

food_trucks = [{name: "Baja Taco Truck", description: "Features amazing tacos, burritos and tostadas made with Carne Asada, chicken and fish prepared as it is in Baja.", website: "http://bajatacotruck.com/"},
               {name: "Benny's Crepe Cafe", description: "New England's best traveling Crepe Cafe. Named after owner Frank Shear's grandfather Benny, they provide nutritious and fun breakfasts and lunches for business people along Route 128 and in Boston. In addition to their truck they also cater parties and corporate luncheons.", website: "http://www.bennyscrepecafe.com/"},
               {name: "Bon Me", description: "Bon Me is run by Boston-bred husband and wife duo Patrick Lynch and Ali Fong. The business was born in 2010 when the two decided to enter the City of Boston’s Food Truck Contest on whim and surprised themselves by winning. With their win came the opening of the first Bon Me truck in 2011. Three years and lots of sandwiches, rice bowls, and noodle salads later, Bon Me has expanded to four bright food trucks and a restaurant in Kendall Square. All locations are proudly serving the Boston and Cambridge communities bold, fresh, and fun Vietnamese cuisine.", website: "http://www.bonmetruck.com/"},
               {name: "Boston's Baddest Burger & Sandwich Co.", description: "At Boston’s Baddest Burger, our recipe for success is our combination of great food, great service, and even better prices. From food truck burgers on the go to corporate events and even on-location catering, we’ve got all the ingredients to make Boston’s Baddest Burger Food Truck the best in the city and beyond. We use only the freshest ingredients from local sources to bring incredibly good food and reasonable prices right to your door. We get our delicious bread and rolls from Iggy’s, a Cambridge-based bakery. We use all Kenneally meat, locally owned and operated in the Boston area since the 1930s, for fresh never frozen, high-quality meat products. We get our produce fresh every day and stock the best in cheeses (Cabot, and more) and toppings. We even have Boston’s Baddest exclusives like Stella’s Homemade Hots made especially for us and Jalapeno Bacon – we’re the only carrier in New England! For amazing burgers, deli sandwiches, soups and anything else you could imagine, Boston’s Baddest Burger has got it covered! Whether you stumble across our truck in the city for lunch or you have our truck come to you at your event (with any menu!), there’s something for everyone at Boston’s Baddest Burger.", website: "http://www.bostonsbaddestburger.com/"},
               {name: "Cameo Macaron", description: "Cameo Macaron is Boston's first French Macaron retailer and Food Truck. We are extremely excited about sharing our favorite piece of France with you!", website: "http://www.cameomacaron.com/"},
               {name: "Captain Marden's Cod Squad", description: "The Cod Squad is serving up Captain Marden's award winning exclusive fresh seafood & organic produce creating a traditional New England experience with a twist!", website: "http://www.cmsfoodtrucks.com/"},
               {name: "Chicken & Rice Guys", description: "After a night out in New York City, we were introduced to the wonder of eating Chicken and Rice outside with our friends. We became instant addicts! (Does this sound familiar?) Since that night, each visit to New York City had to be accompanied by a meal of Chicken and Rice, either from the Halal Guys on 53rd and 6th, the Meatpacking district, or Brooklyn with their famous green sauce. So we thought “Why is there no Chicken and Rice in Boston?!” With its popularity and lines down and around the block in New York City, it was obvious that Boston was missing out on something incredible. Plans started to hatch in July 2011 for Beantown to have its very own Chicken and Rice food truck. Since then, support from our customers has been incredible! In 2 short years, we have expanded to 3 food trucks, a thriving corporate catering business, and hopefully will be opening our first restaurant. As we grow, our goal is to be the next fast casual chain that serves delicious food, provides great service, and gives back to the community.", website: "http://www.cnrguys.com/"},
               {name: "Chubby Chickpea", description: "The Chubby Chickpea is your source for the best Mediterranean food in town.  We have a huge selection of handmade falafels, stuffed grape leaves, rotisserie Shawarma, fresh hummus, baklava and more.  If you want healthy, fast, and fresh, look no further than The Chubby Chickpea! Our restaurant is based in the historical Massachusetts town of Canton, and is Glatt Kosher under the supervision of the KVH.  You can also find our Kosher (KVH/Vaad) food trucks during lunch hours in Boston on the streets of Back Bay, The Waterfront, and Financial District.  Our Catering department is perfect for your small or large private event.", website: "http://thechubbychickpea.com/"},
               {name: "Clover", description: "Our food philosophy is driven by simplicity. I’d rather have you shocked by how delicious our turnip soup tastes than impress you with an exotic ingredient or fancy technique or flowery menu description. We try to keep everything very simple, but very careful. If you eat with us for breakfast you know that we’re making the soup or salads in the morning and prepping for lunch. We don’t make ketchup. We don’t make Mayonnaise. We make just about everything else every day. This is Fast Food. We’re obsessed with speed and constantly time ourselves. Our average serve times are around 3.5 minutes, which makes us a little slower than McDonald’s.", website: "http://www.cloverfoodlab.com/"},
               {name: "Compliments", description: "Compliments Food Co was born in Jan 2012 when Kim Crocker and Bobby Maclean bought one way tickets to California. Their mission was to bring back a little white step van to Boston and turn it into a food truck. After a long drive and several months of ordering and installing restaurant equipment a food truck was born. The menu was written and spots acquired, but what would set them apart from the rest? The answer, local farms and fresh food. Take great ingredients and prepare them right in front of you! Everything is made to order with their secret ingredient Pure Love. Stop by the truck and see what makes them so special!", website: "http://complimentsfood.com/"},
               {name: "Cookie Monstah", description: "We are a Boston based food truck serving homemade cookies and ice cream sandwiches made with love and the best ingredients available. We bake cookies throughout Boston.", website: "http://thecookiemonstah.com/"},
               {name: "El Diez Argentenian Grill", description: "Good morning!! We had the truck out on the streets of Somerville yesterday parked outside of a test kitchen where we were refining our recipes for our empanadas and chimichurri. I am very excited about the buzz that this generated as I have gotten many phone calls and likes on this page that has been a bit neglected. We have a rough go-live date for the 3rd week in June as we are still waiting on final approval for our site locations in the City of Boston.", website: "http://www.eldiez.us/"},
               {name: "Evan's NY Style Deli", description: "Evan's Deli career started in the late 1980's, at Michael's Deli in Marblehead, where he studied under the tutelage of Michael Sobelman, and learned the true meaning of what Evan likes to call 'Deli-ology!' In 1992, Evan moved to New York, the 'birthplace of deli.' where he continued his deli education at the Stage, Carnage, and Katzes Deli, becoming great friends with the owner of the Stage Deli. It was here in the birthplace of Deli Evan earned his 'PHD in Deli-Ology!!!' After moving back to Massachusetts in 2007, Evan noticed a striking need for a true New-York style Deli in Marblehead. In August of 2007, Evan's Deli opened it's doors on 31 Smith Street, and it has become Evan's goal to bring a true taste of New York to Marblehead, MA. In 2014, Evan decided to bring 'Deli-Ology!'' on a Food Truck to Boston. Evan's New-York Style Deli Food Truck is all over Boston serving breakfast, lunch and dinner. The Food Truck menu is a selection of the most popular items on the Deli menu in Marblehead. With fresh deli meat from NY, our Deli & Food Truck are truly bringing New York to Boston!", website: "http://www.evansnewyorkstyledeli.com/"},
               {name: "Frozen Hoagies", description: "Opening on July 4th, 2011, Frozen Hoagies is Boston's original ice cream sandwich truck. Homemade cookies and hand scooped ice cream combine to make the perfect cool treat for those hot summer days. Our cookies are the product of a labor of love and family recipes. Our ice cream is locally sourced from Chilly Cow in Arlington. It is hand made in small batches using only the finest ingredients.", website: "http://frozenhoagies.com/"},
               {name: "Fugu Truck", description: "Fugu Truck is dedicated toward bringing authentic Asian street foods to Boston.  Working with pristine and locally sourced ingredients, Fugu Truck creates seasonal and flavorful Asian dishes that is sure to please all palates. The name Fugu was inspired by the fugu fish, a unique and sensational delicacy in Asian cuisine.  The preparation of fugu requires an utmost level of devotion and rigorous training.  While the Fugu Truck will not be serving the fugu fish, it embodies the discipline, dedication, and sophistication we hope to bring to our dishes!", website: "http://www.fugutruck.com/"},
               {name: "Green Bean Mobile Cafe", description: "What if every cup of coffee Americans purchase went towards a good cause? From this thought, Green Bean Mobile Cafe was born. At Green Bean Mobile Cafe, you can purchase rich, organic, fair trade coffee knowing that a portion of the proceeds will be donated towards Boston’s green initiatives. To eat, Green Bean Mobile Cafe offers a variety of delicious options – from coffee cake and bagels made by local businesses to Belgium waffle and unique panini sandwiches made onboard the truck. Just think of the impact that can be made if a small fraction of coffee drinkers switch to Green Bean Mobile Cafe.", website: "http://www.ilovegreenbean.com/"},
               {name: "Latin Spoon", description: "Latin Spoon is now serving up their menu on Boston's streets. What's on that menu? Well, empanadas for starters. Perhaps more intriguing is an item they call a 'Pata-Kone' — a cone-shaped shell of fried plantain stuffed with skirt steak, avocado, cilantro, and cheese. The truck is currently on the city's schedule vending both breakfast and lunch. Stops include Trinity Place and Cleveland Circle.", website: "http://www.thelatinspoon.com/"},
               {name: "Lilian's Smokin' Rack BBQ", description: "We provide high quality barbecue dry rubs to allow family and friends to share in the experience of Texas-style barbecue in the comforts of their own home. All our products are hand-blended in small batches using premium quality ingredients. No artificial flavors, additives, or preservatives are used.", website: "http://www.liliansmokinrackbbq.com/"},
               {name: "M&M Ribs", description: "M & M Ribs food truck in Boston serves BBQ dishes.", website: "http://mandmribs.com/"},
               {name: "Makin' Jamaican", description: "The most authentic taste of Jamaica you'll find in Boston! Jamaican Food Truck!", website: "http://www.makinjamaican.com/"},
               {name: "Mei Mei Street Kitchen", description: "Our award-winning food truck serves creative Chinese-American cuisine made from locally sourced, sustainable ingredients. We pride ourselves on serving humanely raised meat, produce from small farms, and some of the most creatively delicious street food out there. Click around to learn more about us, the three sibling founders, and how we try to run our company. Or get the latest word by following us on Twitter, Facebook and Instagram. We’re even up on Pinterest if you want to peruse photos of our food, farms we love, food truck weddings, and other fun stuff. See you on the streets!", website: "http://meimeiboston.com/"},
               {name: "Momogoose", description: "Long lines everywhere we go, Momogoose is Boston’s first gourmet food truck. In 2011, Momogoose was the winner of the Boston Food Truck Challenge.", website: "http://www.momogoose.com/"},
               {name: "Moyzilla", description: "Our goal is to bring the freshest, most creative Asian street food and dumplings to the streets of Boston and beyond. We specialize in creative takes on the ultimate Asian comfort food, the dumpling! From our staple pork and napa cabbage dumpling to out-of-the-box ideas like our “Moyzilla Style” cheeseburger dumpling we passionately believe the dumpling is the perfect vehicle for yumminess. Our love for dumplings is only matched by our love of classic and creative takes on all other kinds of Asian comfort Food: Moyzilla skewers with unique sauces, rice/noodle bowls, and inspired sandwiches and noodle soups – all using the freshest ingredients. We only hope you enjoy eating our food as much as we enjoy serving you!", website: "http://www.moyzillaboston.com/"},
               {name: "Paris Creperie", description: "La Tour Eiffel - Boston's First Crepe Truck. Check out our full schedule on our website.", website: "http://pariscreperie.com/"},
               {name: "Pennypackers", description: "We are a family run business in the Boston area with 2 food trucks, a catering business, and a brick and mortar restaurant. Our truck and restaurant menu changes daily, featuring specialty soups, salads and sandwiches- the only item that stays on daily is our specialty, Porchetta. Porchetta is an Italian, skin on roast pork- heavily seasoned, cured and marinated in herbs and garlic. We serve it with a variety of toppings, such as onions agrodolce, marinated broccoli rabe, seasonal mostardas, and lemon juice and arugula.", website: "http://www.pennypackersfinefoods.com/"},
               {name: "Redbones Barbecue", description: "Redbones is a well established, much loved restaurant located in Davis Square - Somerville, Massachusetts. RedBones has become a favorite for many folks over the years, most likely due to its authentic downhome-style Southern food, its unique ambience, and the genuine friendliness of its staff. Redbones also offers 24 fresh microbrews on tap and often hosts local Brew Fests. Catering and delivery are available for private functions. ", website: "http://www.redbones.com/"},
               {name: "Rhythm 'N Wraps", description: "Make your special event extra special with great food and service by Rhythm n' Wraps Vegetarian Catering.  We offer full service catering to the Boston Metro area for events of any size with our large mobile food and beverage truck and all necessary equipment. We are very flexible, and will deliver excellence to any type of event, large or small, customized and tailored to the clients needs.", website: "http://rhythmnwraps.com/"},
               {name: "Roxy's Gourmet Grilled Cheese", description: "We don't make your grandma's grilled cheese. We can if you'd like us to, but if you leave it up to us, we're going to put our own twist on things. We're about taking grilled cheese to the next level by adding ingredients you never really thought possible.", website: "http://www.roxysgrilledcheese.com/"},
               {name: "Savory Food Truck", description: "Our company started in May 1992. Our main focus is Chinese food business. Over the years, we operated several Chinese restaurants. Eventually we decided that Chinese style fast food is our niche. Our food truck provide high quality, convenient and economical Asian meals to our customers. We have more trucks ready to serve our customers, please feel free to contact our management team.", website: "http://www.savoryfoodtruck.com/"},
               {name: "Sheherazad", description: "Brining fresh, local, and boisterous home style Middle Eastern food to a modern world. Straying from the norm!", website: "http://www.sheherazadfood.com/"},
               {name: "Stoked Wood Fired Pizza Co.", description: "We strike a balance between the best pizza available in its birthplace, Naples Italy, and the best coal oven pizzas found in New York and New Haven. We prefer a pizza that is soft and light on the inside with a crispy outer shell. To achieve this we use ancient technology - a wood burning oven - for the superior flavor it imparts. Our fast 2-3 minute bake time allows us to retain the fresh and vibrant flavors of minimally stressed ingredients while also achieving a crispy crust that has just the right amount of char and character. We use organic flour, a blend of California and Italian organic tomatoes and an artisan pepperoni. At Stoked wood fired pizza company we source organic and local produce whenever possible, and our chicken is naturally raised. We use aged mozzarellas like those popular in the New York and New Haven areas, with their crave-inducing salty and buttery dimension. The combination of all of this is 'pizza heaven', a perfected artisan pizza that is the best of all worlds.", website: "http://www.stokedpizzaco.com/"},
               {name: "Sweet Tomatoes Pizza", description: "The Sweet Tomatoes Pizza Truck is available for Catering and we would love to work with you to provide our delicious pizzas and salads on-site at your event. Our truck can cater just about any occasion from a backyard party to a full corporate event or an awesome wedding after-party!", website: "http://sweettomatoespizzatruck.com/"},
               {name: "Taco Party", description: "The best veggie joints I’ve been to are the ones that I can sit across the table from my carnivorous pals and they don’t even bat an eyelash. That’s what this is about. Eating well together. I’m not going to preach to you. To each their own. Everyone is free to put whatever they want down their gullet. I’m just here to offer you something a little different and we’re gonna do it in the most sustainable and eco friendly way possible. I’m also not going to claim any authenticity here. I reserve the right to put anything I damn well please in a tortilla. The menu will mainly have Mexican roots but don’t be surprised if things get weird from time to time. Just like a regular party, a taco party can get a little out of hand too.", website: "http://tacopartytruck.com/"},
               {name: "Tenoch Mexican", description: "Tenoch Mexican brings authentic, affordable, high quality Mexican food to the Boston area. ¡Buen provecho!", website: "http://www.tenochmexican.com/"},
               {name: "The Bacon Truck", description: "The Bacon Truck proudly serves Blackstone St. Smokehouse's thick-cut, applewood smoked bacon. Prepared and smoked right here in South Boston, it's the best bacon around. Next spring we'll be selling it by the pound at our truck for you to take home and cook yourself!", website: "http://www.bostonbacontruck.com/"},
               {name: "The Dining Car", description: "The Dining Car is a mobile food truck and catering company – a kitchen on wheels, serving freshly prepared meals on the streets of Boston. Our sandwiches are made on great breads, and our focaccia is baked right on the truck, continuously throughout the day. Our ever-changing menu features meats and seasonal produce that represent our local agricultural community, with selections inspired by cuisines from all over the world.", website: "http://www.diningcar.net/"},
               {name: "The Pasta Pot", description: "The Pasta Pot is a family owned and operated 'restaurant on wheels' operating mostly in Boston, serving at special events all over New England. We have new twists on all your italian favorites. Our signature dish is our famous Meatball Mac & Cheese! It's to die for!", website: "http://thepastapot.com/"},
               {name: "The Taco Truck", description: "The Taco Truck was born out of an adventurous and extraordinary idea - to bring the authentic Mexican taqueria cuisine that we love so much to the East Coast. With our entrepreneurial spirit and desire to create unique and inspiring brands in tow, we set out to bring this authenticity to the nation in an experimental way: a food truck. In 2009 we launched our very first truck in New Jersey. It turns out we weren’t the only ones craving authentic Mexican tacos, and with a commitment to sustainability we’ve forged ahead. So far we've opened stores, kiosks, carts, and trucks in NY, MA, and NJ - and we're only getting started!", website: "http://thetacotruck.com/"},
               {name: "Uyghur Kitchen", description: "As one can imagine the food of the Uyghurs are largely influenced by the historic exchange of goods in this area, making them mostly traders. Xinjiang’s harsh desert terrain is largely uncultivable, but a system of irrigation introduced by the ancient Uyghurs created “oases,” allowing people in this area to begin cultivating vegetables, wheat and fruit. These oases are famous for producing sweet melons and grapes. However, the feature food of the Uyghurs is the incredible Lamb Kebab, often simply prepared allowing the quality of the meat to shine. Lamb Kebabs roasting over coals and nan, a leavened flatbread cooked in a Tandoor oven, are common street foods for Uyghurs.", website: "http://uyghurkitchen.com/"},
               {name: "Barbecue Lamb Brothers", description: "Founded on July 1st 2013, Wow Barbecue began serving authentic Chinese Barbecue (food on a stick) on the streets of Boston in a bright red food truck. Along with 10 other partners, Wow Barbecue was founded and currently managed by Babson College MBA graduate Steve Liu. Most recently Wow Barbecue has expanded into two food trucks and opened a brick and mortar restaurant in the city of Malden, MA. Our mission is to introduce this delicious, and totally foreign food to the city of Boston and furthermore to provide a taste of home for all Chinese nationals working and studying in the area.", website: "http://www.wowbarbecue.com/"},
               {name: "Zo on the Go", description: "A few years back while visiting Greece and sampling some authentic Gyros, we discovered the great taste that was centuries in the making, but not for sale in the Boston Metro area. After being in the restaurant business for years, we knew that authentic Greek cuisine would be embraced by businessmen, tourists and foodies alike. Come discover a new taste and why it’s worth the trip. It’s Zo Good!", website: "http://www.zoboston.com/"}]

food_trucks.each do |info|
  info[:user_id] = User.pluck(:id).sample
  if !FoodTruck.exists?(info)
    FoodTruck.create!(info)
  end
end

FoodTruck.all.each_with_index do |truck, i|
  truck.truck_photo.store!(File.open(File.join(Rails.root, "/food_truck_images/#{i}.jpg")))
  truck.save!
end

reviews = [{description: "Yum!  Bacon Bit Sammich was amazing.  I like the uniqueness of this truck and that they focus on a few great items.  Staff was friendly and efficient."},
           {description: "I wasn't impressed as I thought I would be! Yes, the dumplings were delicious, but I was hoping to get more of the food truck experience they offer and try a few items. Its harder to do that at the store, because all items are $7+ and it can add up quickly. However, they had some creative options available that all sounded good, and I love the space. So, I'll bump this place up to four, but I prefer the truck."},
           {description: "We had their food truck 'cater' our 6/14/14 wedding and it was amazing... All our guests loved the uniqueness of the menu and also loved the locally sourced food aspect!"},
           {description: "The food was good, everything was tasty and its a nice place! Definitely would come back!!"},
           {description: "Awesome!  Seriously everything was awesome.  No frills, nothing fancy? Just simple portions, but each bite with so much flavor and love.  You can seriously taste the love in their dishes.  The house made pickles that come with the pork dumplings are great!  Exotic and reminds me of Taiwan. Actually they looked like celery and not pickles at all but I got what they were aiming for..."},
           {description: "Always a struggle to find quality delicious halal food, and when visiting Boston I knew I had to check this place out. There's always a line because everyone knows how good it is. The menu is simple, chicken, lamb, or combo and comes with a plethora of rice and lettuce and a little bit of pita to satisfy that middle eastern craving you have. Not much more to say other than the food is reliably and consistently amazing, and the $7 price can't be beat. "},
           {description: "At the downtown location the meat can be a hit or miss. In our group's case if you're a guy you get chunks of chicken and a pretty plate of food, if you're a gal you get scraps and stuffs tossed together... Yellow rice, you can't go wrong with that. I love how they grill the pita. Chicken and rice is a staple, but maybe not from the people who run this truck. The food is still good nevertheless."},
           {description: "Good, basic Halal fare. I had the straight up chicken dish which was definitely great. The sauces are tasty -- you add them yourself -- but watchout, the 'milder' red sauce is still pretty hot. Next time I'll mix in some yogurt sauce to cut the heat. Great price too."},
           {description: "If i had to complain about it, I would say that without the condiments, the food is actually a little dry and a tad bland.  However, it's the condiments which make the food absolutely delicious.  You will absolutely drench your food in the white garlic sauce.  For people who like spicy food, you'll apply some of the hot sauce."},
           {description: "his was my first food truck experience. I had high expectations. The plain grilled cheese was average and really greasy. Needed a napkin after every bite. The pulled pork grilled cheese was way richer and pretty good. I would rather use the calories on something else. Truffle fries were very flavorful but went soggy fast."},
           {description: "Good God, this place is seriously the bees knees. My friends send each other text alerts every time we are in vicinity of the food truck. The service is great, I seriously love the people that work for this truck and they really seem to care about the food and the customers. I studied abroad during the fall and I was really upset that I couldn't get the fall melt because it was SO SO GOOD. I would work hard at the gym all week just to get that cheat meal. Since I'm vegetarian, I typically get the three cheese melt year round. This is the type of food truck that's worth chasing and if you are visiting Boston make it a point to grab a bite."},
           {description: "We found the truck next to Boston City Hall, buried behind a mass of people cueing for cheesy goodness. I got the Green Monster- and it was quite tasty - Munster Cheese, guacamole and bacon on white bread. Everything was fresh and quickly made. My only complaint (and it's a small one) was that it wasn't messy enough. The cheese was too contained within the bread, and you didn't get the ooze factor one sometimes wants from comfort food. The fries were also pretty amazing and were doled out rather generously."},
           {description: "One of my go-to's for lunch during the week when it is parked downtown. I like the 3 cheese with bacon but would enjoy it a little more if it wasn't as dry. Add more butter to the bread please! Their rosemary sea salt fries are perfectly cooked and tasty! Need more drink options. My only other complaint is the waiting time to actually get your food. It takes a big chunk out of my lunch break. Booooo"},
           {description: "OMG, that's all I have to say! I purchased the Mighty Beef and truffle fries. The sandwich was AMAZING!! I love the BBQ beef and melted cheese, sooooo goooood. The truffle fries were awesome!!! It smelled the entire office so I had to offer my coworkers some. One even loved it so much he went to purchase his own! Definitely a must come back every Wednesday by Prudential! My new favorite food truck!!!"},
           {description: "I don't know what to tell you. If you don't think this is the best food truck in Boston, you are dead wrong. Believe the hype train because it is about to run you down. Choo choo, motherfucker. Every sandwich I have had at Roxy's might be the best sandwich I have ever had. They are so buttery and warm. The Mighty Rib in particular is delicious. Utterly phenomenal. The fries are also as good as other reviews have said. Stop by. You won't regret it."},
           {description: "This food truck is kind of hit or miss for me. I'm not a huge fan of their breakfast options. I ordered the breakfast sandwich once, after ten minutes I was handed a half pita with a hardboiled egg and raw tomato slices inside. Their lunch sandwiches are excellent, though. The chickpea fritter sandwich is just as great as everyone says. They also do monthly special sandwiches, my favorite of these was the Enzo which had eggplant and those delicious rosemary fries in it, I wish they'd bring it back! Staff is friendly and laid-back, but sometimes service can be slow. It's a great healthy alternative to fast food lunch."},
           {description: "My co-workers and i used to religiously come here a few times a week  We've literally tried everything on the menu and we've never been disappointed. The egg with eggplant and the chickpea sandwiches are to die for! Now i'm suddenly craving their egg and eggplant sandwich and their hisbiscus lemonade, but i'm not in Boston today. Really miss all that yummy goodness. "},
           {description: "First food truck experience with many more to come! The chickpea sandwich carried a one-two punch that kicked my taste buds outta my mouth. My only concern is that if you come here during rush-hours, it may take up to 20 minutes to get your food, but hey, sometimes it's worth waiting for something great! Totally didn't know it was a vegetarian stand, but that didn't stop my from enjoying the meal!"},
           {description: "On the menu they have a picture of 2 tacos for $4, but when I received it, turns out only one tiny taco as a size of my palm, it's such a misleading, i wished I remembered to take pictures of both the menu and the food I got. The taco itself was so bland, the meat was dry and lack of flavor. I was expecting high when I read the reviews, but it was very disappointing."},
           {description: "After speaking with the owners of the truck, I was impressed by the background of the chef, Bing (sp?). A graduate from Le Cordon Bleu in France, he has worked in a few Michelin starred restaurants in France and New York City before starting Fugu with a few friends. The high quality of the food on truck is definitely a reflection of his talent and passion for food. "},
           {description: "5 star rating for their pork belly bun. Belly was perfectly braised, seasoned well and complimented nicely by the subtly sweet steamed bun. Also love their bibimbap. Can't go wrong with rice, kimchi and Korean pork. This place is definitely a gem when it comes to Asian street food."},
           {description: "Delicious food truck with Asian-inspired food. I've only been here once, but I'd definitely eat here again if I had the chance. Must gets: Braised pork belly with steamed buns - Hard on the coronary arteries, easy on the taste buds! Delicious fatty and salty slices of pork sandwiched between soft and fluffy buns. This is some high quality stuff here."},
           {description: "Such a great addition to the Boston food truck scene. The cold noodles (ask for extra spice!) are great on a hot SOWA Sunday. The grilled pork buns are different and tasty - Haven't seen them on the menu recently, but hopefully they'll make a comeback? I love that they change their menu pretty frequently -- am dying to try their ramen. I wish they posted their daily menu on twitter, but that's something that can easily be changed, right?"},
           {description: "Great quality, great presentation, great taste! That being said, this place is about 25% more expensive than any other food truck I frequent, and the portions are a bit small. While perhaps not the best value, the bibimbop is so yummy that I get it anyway. Unlike most food trucks, this truck neatly presents food in its containers, rather than simply dumping it in them."},
           {description: "Some of the best pork buns you will find in Boston are sold on a food truck!  Everything I've had from this truck has been great, plus the owner, Bing, is a pretty funny guy."},
           {description: "This is actually a very good and decent food truck. I got the Chinese BBQ pork rice bowl. It was very good and cheap. For $6.50 I was satisfy and full. Some people think it's too salty but I thought it's just where it should be. I would definitely get food from here again."},
           {description: "I had the coconut chicken over rice. Wow. Really healthy tasting but flavored galore and very generously sized!  They didn't specify the chicken would be shredded, which made it even better. Really good. Ordered the side of edamame which was legit 5 pieces cold.  That was weird. My complaint. My hubby got the pulled pork rice bowl which he also loved but it was a tiny bit too greasy to feel healthy."},
           {description: "This is my favorite food truck. Tofu rice noodle salad is the only thing I order there, because it never disappoints. Tried pork once it was too try and salty. Soba noodle texture is less reliable than rice noodle, sometimes it gets soggy."},
           {description: "Fresh, highly flavored, but complex and not just blahspicy. On the most amazing baguette I have had in years. I feel like if you are getting the bowls, you are denying yourself something truly great. I would eat this once a week if I were in the neighborhood."},
           {description: "I love this food truck. Its super cheap, all vegan and very very tasty as well. I just wish they were near Jamaica Plain too - so I don't have to go up to Chinatown each time I want to eat these. The plaintain taco is pretty awesome."},
           {description: "Today was my first visit to this truck and I fear I might stalk them now.  This food is AMAZING.  Doesn't matter if you're vegan, gluten free, vegetarian, or an omnivore - the food is just delicious, fresh, flavorful, interesting, and filling no matter your preferences.  I got a meal - the buffalo tempeh taco, sweet potato and rice and beans on the side.  The people working the truck are so nice and friendly, the service is great and the food rocked my world.  I will be a regular every time they're close to my office and I might just follow them around Boston if I have the time.  Run, don't walk.  I am so excited this food truck exists!"},
           {description: "This truck! So glad I finally got to check it out & boy is it tasty. I mean what are the chances of having an all veg food truck, so glad they're here!"},
           {description: "I'll be back! There were only two tacos that did not include cilantro in prepared salsa. Sweet potato and Seitan tacos were both fabulous! Two tacos filled me right up--generously stuffed, but could still eat them  neatly."},
           {description: "I am slightly obsessed with this place. I've only had it a few times when I go to SoWa market since it's not located near me. Although, if I had one near me it would dangerous. The tacos are so good and I love the creative names! I love the buffalo and seitan ones. The times I've gone there weren't any desserts, bummer! Still, this is my favorite food truck. Also, everyone who works there is super nice and friendly! If you haven't tried this food truck, go NOW. You won't be disappointed!"},
           {description: "Holy Crap. I can't handle my love for this truck. Vegan Mexican food? Heck yes. I LOVE the tempeh tacos. Seitan is still a little weird to me, but I've heard good things about the Seitanthony's Feast. Maybe next time. Anyway, it's really great having another forward thinking truck on the growing food truck scene here in Boston. "},
           {description: "Yummu yummy YUMMY vegan food truck! Love being able to order whatever I want there -- love the tofu, the buffalo, the chips and bean dip, the rice and beans ... love it ALL. They take Level Up if you are lacking cash, and they have awesome Ugli hot sauce available for dotting your already delicious tacos with, which is great if you're a spice-head like me. A must try! Get the meal for $10 with two kinds of tacos and a side."},
           {description: "Consider this me jumping on the bandwagon. Absolutely delicious!! My weakness is cookies (chocolate chip, especially). After a particularly grueling workout I found myself in Copley Square and proceeded to indulge in an ice cream sandwich."},
           {description: "Recently had to go gluten free and was so happy to find a gluten free cookie here last week in Dewey Sq.  I went to get a cookie today and was so upset to find out they only have them on Friday.  Do you think we only eat on Fridays?  Lost my business, sorry.  Plenty of other places to get mediocre sweets that are gluten free near South Station."},
           {description: "The cookies are so good that you can actually smell them before you get to the truck. Everything is freshly baked so it's always amazing. The chocolate chunk cookies are the perfect ratio of gooey:crispy, aka amazing. The ice cream sandwiches are amazing (and huge) as well. This place is always a winner!"},
           {description: "I've visited this truck many times in front of MGH. Their cookies are delicious, warm, and they often will give me an extra cookie if I say something cute or funny. Not sure why, but it's happened like 3 times."},
           {description: "Walking through Chinatown I have a few spare bucks they will always be given to the big red truck."},
           {description: "I don't see what the hype is about. I was super excited to try this food truck because people told me how great it was. To my disappointment, I didn't like any thing about it. I paid $1.50 for a small skewer of super dry and over-seasoned meat. NO THANK YOU. Not to mention, the service was super slow and they messed up my order. I ordered one thing. How can you mess that up? I will not be back and will never understand people who buy a whole batch of them."},
           {description: "If you're in the area and you want a delicious, cheap, Atkin's friendly snack, then there's really no better option that this truck. I recommend the chicken and the lamb."},
           {description: "Many times I've gone to lunch wishing I could have a little snack afterwards. Meat on a stick is a snack as good as any. I usually find this truck across the street from the RMV in Chinatown. I pass by on Wednesdays to get my fix. Generally what you see is exactly what you get. They''ve got various meats and some non-meat items grilled for your munching pleasure conveniently prepared for on the go eating."},
           {description: "Lamb skewers are AMAZING! Definitely get them with the spicy powder."},
           {description: "Tried the chicken and lamb kabobs they were dry over-seasoned and really fatty.  Also they did not accepted their own coupon.  Really cheap, but i think I know why now."},
           {description: "I have been eyeing this red truck in Chinatown and one day my husband and I caved in to get a couple of skewers.  We got both beef and lamb skewers.  The skewers were $1.50 each.  The beef skewer had a bit more meat but I thought the lamb skewer was more flavorful and juicier. We asked for ours spicy but we thought it was mild. Great place for a quick snack."},
           {description: "The lamb skewers are perfect. They're just like the ones in China. The price ($1.50) is a bit on the expensive side, but it's worth it as a snack."},
           {description: "Stumbled upon this truck by chance in Chinatown Boston and ohhhh so good! I mean when are Chinese lamb skewers ever bad... Also tried the quail egg skewers and they were pretty good as well. Just a tad pricey if I recall... Regardless, we need more of these trucks selling spicy lamb skewers around, seriously!"},
           {description: "Skewers for 1.50!!! Great and tasty deal, had the chicken, shrimp, lamb, and quail eggs, by far the best ones were the lamb and quail eggs!"},
           {description: "Omgosh - the Porchetta sandwich is something I wish I could eat everyday. The time I went I was hanging over a little and it couldn't have been a better cure. The guys working the window was super nice too especially when I requested to not get the pickled peppers and just get onions and the apple puree that they had... MMMMMMM  :) I can't wait to get another one."},
           {description: "Had a porchetta and mushroom soup. I know the porchetta is supposed to be fatty but I felt mine was overly fatty. The cream of mushroom soup was a little disappointing, it almost tasted like it had been sitting for a while."},
           {description: "Nice zucchini soup, although a bit on the oily side. Good way to warm up in the cold weather though!"},
           {description: "Really happy to see a food truck with food of this caliber in Boston. Definitely not your average fare. Well thought out sandwiches on quality bread, unique salads, and everything is homemade. Think less greasy food truck, and more 'flour' on wheels. Better than flour in my opinion. Had the porcetta sandwich and my girlfriend had the caprese. Both awesome- incredibly flavorful and for $6 each, a lot of food. Can't wait for the next time I'm in the area so I can hit up the truck again."},
           {description: "I catch them for lunch when they're at St Mary's Street and Comm Ave on BU's campus. The menu didn't really grab me at first, but the food is DELICIOUS. So far, my favorite seems to be the Caprese sandwich. (It's made with goat cheese!) My coworkers love the Porcetta, and I also heartily approve of the gazpacho they have on occasion. The service is prompt, and the employees are very attentive. It's a great change up from the usual campus food!"},
           {description: "I can definitely depend on this food truck for days I forget my lunch. They always strive for interesting food. And they accept CC (!!!)."},
           {description: "I ordered soup. Cold soup. You pour it in a cup. We waited 20 minutes, and then watched as they put a cup in a bag for me that had been sitting off to the side of the pick-up window for the entire time. They also don't wear gloves when they make sandwiches, handling them instead with bare hands. Not the greatest service skills I've ever seen, and I've been in the restaurant industry for 15 years. The food itself was decent. We'd gotten sandwiches from here about a month ago that were pretty good as well. Biggest take-away from this: order your food ahead of time."},
           {description: "Unbelievably good. A true diamond in the rough.  By far one of the best sandwiches I've had in boston.  The menu changes often, and the food is top notch. I would highly recommend. More locations please."},
           {description: "I go to this truck at least once a week - usually more.  I LOVE how they have vegetarian options every day! I try to eat little to no meat in my diet - they make it so easy and tasty! Thanks guys!  keep it up!"},
           {description: "The Porchetta  and Grilled Chicken sandwiches were delicious. Sometimes the wait is a little long due to its popularity and the amount of phone orders they get, but it's worth the wait.  Maybe I'll call it in next time as well."},
           {description: "The truck was in Kendall Square today.  I had the General Gau's (salty), crispy roll (ice cold? WTF!), over rice (mostly cold). Food temp problems, I'd say."},
           {description: "I keep giving this truck a chance and I've decided its mediocre at best. I've had the beef ramen, Bbq chicken, Beef Bulgogi, Curries in different ways: over rice, ramen and the sandwich.  Every time I have eaten I wish I ate somewhere else. Ramen noodles were limp, overcooked. The rice plates make me feel like I ate an entire salt lick.  The plates are only $6, so you really get what you pay for. The people that work the trucks are nice and the portions are good,  but I'm not a fan."},
           {description: "This is a great food truck. Today we went there got lunch and I had the tofu ramen. You can get a whole meal with a main dish, dumpling or spring roll and a drink for $8! You can't really beat that! The ramen was very good! It is in a savory vegetable broth. If you see this truck, you should drop by and pick up a great lunch!"},
           {description: "Stopped by for some lunch today and was surprised... twice. First, the line for the truck was huge. I thought I'd be there the whole lunch hour... man was I wrong. It took maybe 5 minutes. On top of that, the food was awesome. I got the chicken Thai Peanut over Egg noddles, with a crispy roll, and Lemonade, and it was only $9."},
           {description: "I eat lunch here weekly.  I love the beef ramen, daily specials and soups.  Add a little hot sauce and -yum!  Super friendly and helpful employees and exceptionally reasonable prices.  Keep it up!"},
           {description: "I give this place 3 stars- an in between for their 2 star food and 4 star service. Food here is very lightly flavored. Portions are considerable for the $6 value, but it's really not that impressive. Service is great though. Julius is very friendly (though he didn't hook us up as he promised in his tweets to my friend). Do note: THEY DON'T SERVE BREAD ON FRIDAYS. Apparently they're 'not allowed because of competition' Something like that."},
           {description: "This is one of my regular lunch destinations in the  FiDi.  How can you beat a $5 lunch special? The tofu baguette is my usual (watch out for the hot peppers) but I sometimes deviate and eat the special. Best part (besides the super price and the tasty food)? Super super speedy service. That's essential when you only have 30 min at lunch!!"},
           {description: "I had no idea that this kind of cheap eats would be this good. General Gao chicken (though they do offer tofu), brown rice, crispy spring roll, bottled water: $7.50. Perfect lunch sized portion and it was tasty too! Highly recommend it."},
           {description: "I saw this truck, but had no idea what they served, only that they had won the foodtruck challenge. I ended up walking by with a Vietnamese coworker today and she was thrilled to discover that Momogoose is actually Vietnamese food! She started conversing with one of the staff members who was telling people in line what the specials were. We both ended up getting Nan Goung (sp) mine with chicken, hers with pork. The pork was insanely good."},
           {description: "I'm still eating my food as I write this review, so I'll be brief.  I ordered the steak meal with rice and asian slaw, and words cannot accurately describe how good it is.  They're essentially steak tips in a subtle teriyaki flavor.  However, the steak is VERY tender and juicy and the portions are massive.  Honestly surprised by how good it was.  Better than anything at Tip Tap room and for half the price."},
           {description: "Loved their Japanese fried chicken. Loved the sriracha aioli even more!! Yum yum. Also have to mention I ate there at Boston dragon boat fest and really liked their service too. Will surely be back with friends."},
           {description: "I was very excited for my dumpling and rice dish. It looked great and tasted great, but there was a little piece of bone (well, it felt like a stone!!) in the first dumpling I bit into -- it has likely cracked my tooth. I hoped the initial pain would pass, but It has been three days and I can't eat on the right side of my mouth. :/ I am waiting to see if my ability to chew with that tooth returns. If not, it is going to mean expensive dental work. I imagine people are prepping large quantities of meat when preparing things on food trucks but finding pieces of bone or stone in a dumpling is just not cool."},
           {description: "I've gotten both the classic and the veggie dumplings and they are pretty delicious. Both times I've gotten them with the street noodles, which definitely satisfy my lunchtime cravings. Even when the line is long, you don't end up waiting that long, so still not a bad move for lunch. However, if you can get there at 11, you'll be better off."},
           {description: "Had their cheeseburger dumpling and it tasted like a cheeseburger. Their special sauce really made it! But their classic with pork was blah.  Have also had their box meal with steak and noodle. It was memorable..the noodle were bland and oily.  I find their food to be a bit overprice as well..$5 for 4 dumplings. $8 lunch box."},
           {description: "Not only was the food amazing, but it was cheap! Affordable lunches are hard to find downtown and for $8 I was beyond satisfied. I started following them on Facebook to see where they'd be during the week, can't wait for them to park near my office again!"},
           {description: "Stopped by here for a waffle sandwich one morning on my way home from work (I am a night shift nurse). It was fantastic! I will definitely be returning to this food truck!"},
           {description: "Last year, when I was a wee bit chubbier and hungrier you left me high and dry. You disappeared, with no mention on your Facebook or Twitter page. I would peak down Stuart St. each morning, only to be broken hearted. One glorious day(on my birthday!) you finally returned and I am so happy you did."},
           {description: "This is my FAVORITE morning stop. I work near Copley and they've had one of the morning food truck spots for a while recently. In this area, there's not much in the way of quick breakfast and good coffee that isn't a big chain like Starbucks or Dunkin Donuts."},
           {description: "Excellent way to start the day all around.  Delicious coffee and food and very friendly and cool staff."},
           {description: "I happened upon this truck in the Financial District one day and decided to give it a try.   I ordered the Cheech & Chong with a side of fries (I think it was bacon salt that day).  The burger was cooked nicely (perfect for me, medium well for my burgers) and with fried jalapenos, fried onions and french fries on it, GREAT flavor.  Despite having fried toppings, it was not overly greasy.  The bun wasn't soggy, so that was great (a soggy bun is a so avoidable and a BIG turn off) and the fries were lovely.  I've been back since and I plan to go back every chance I get.  Thanks for a great burger, guys!"},
           {description: "If you are one then you have to try their veggie burger. It seems like they switch up the toppings a lot but recently I had the quinoa/black bean burger with some aioli and added tomatoes and it was so good. The staff was also really funny and were joking around with the customers here and there."},
           {description: "The food here could use some work. I tried a regular burger and I was definitely not too impressed. The fries were super salty and definitely not worth a second try. I came here with my co-worker for lunch and he ended up tossing his burger after a few bites."},
           {description: "I got the Lemmy. It had Jack Daniels bbq sauce and onion strings.  I did not care for the burger at all. Way over cooked. It was almost as if it was par cooked before they grilled it. It was dry and rather unpleasant. The bbq sauce was very tasty. I probably wont be returning. I like juicier burgers then they serve up here, especially for the $7 price tag."},
           {description: "The Lemmy was delicious! A bit on the greasy side but I feel like that's to be expected for a quality burger. The truck made BBQ sauce was one of the better sauces I've had on a burger in a long time. The wait was quick too! Friendly alternative staff."},
           {description: "Great concept and poor execution I guess. I ordered the Lenny which consists of fried onion strings, Jack Daniels BBQ sauce, and some crispy bacon. They even have bacon ketchup which really caught my eye. The bread they used was Ok, it probably would have been better if it was toasted. The burger was way overcooked for my taste."},
           {description: "Good food and fast service, what more could you want from a food truck? I'm usually disappointed with chicken from most Mexican places, but I was super impressed with how flavorful and juicy the chicken was. Overall, I'd definitely eat here again!"},
           {description: "Picked up a California burrito today. Pretty common, nothing super crazy about (although I don't see many places around here that offer them for some reason) Quick service which is always nice. Def filling as well. I'll most certainly be back."},
           {description: "I would give it 5 stars but sometimes the line is painfully long.  Very fresh and tasty food."},
           {description: "Burritos in a truck outside my building for lunch! I've been a couple times now and I've got the Mutt Burrito both times. It is filled with steak, beans, guacamole, a Mexican cheese, and beans. This thing was awesome. It wasn't overly filled with rice either, this was chock full of all the good stuff. The Mutt is even listed on their healthy menu too, I don't know how that is, it tastes too good."},
           {description: "We might be cooking with gas on this one. Today I hive them three stars because the carnitas were bland and tasted boiled rather than broiled. But the fish taco was tasty. A little pricier than my Californian haunts but a-ok."},
           {description: "The Fried Cauliflower ('crispy cauliflower' is what they call it) from this food truck is really excellent, and it's something that I've never seen on the menu at any restaurants around.  I first tried it at the SoWa festival in South Boston and now I get it every time I see this truck.  I haven't tried too much else from their menu, but the fried cauliflower is fantastic and it's gluten free too!"},
           {description: "I had a great Food truck lunch yesterday by South Station, the Chicken and goat sandwich was an amazing mix of flavors [sliced chicken, fresh greens, goat cheese & walnuts]. The wait was overly long so they're lucky I was enthralled by the taste of the sandwich normally I wouldn't have given 4 stars. Arrive at 11:45 and you may have a shorter wait."},
           {description: "I wanted a quick option for lunch and this was very close and fast. I wasn't quite sure what to order so I just got the BBQ pork slider. In hindsight, I should have ordered something else. The slider was pretty small and the flavor was a little off. The pork was also kind of dry and the cabbage didn't really help with anything. Some people got other things and thought it was ok, but I think I just need to oder the dishes they are known for. I may give them another try... but I may not."},
           {description: "Grabbed the slider today, and it was awesome. I was also going to try the bacon brittle, however they were sold out. They did however have chipotle brittle that was pretty good. Definitely a truck to check out."},
           {description: "So, the baguette my goat cheese, walnut, honey and spring greens sandwich came on was pretty fantastic, me finishing it stands testament to that (I'm the 'eat around the carbs' type). The noteworthyness ends there.  The sandwich wasn't bad, and well enough filled, but not particularly harmonious or memorable.  So, at 8 dollars, with no token bag of chips or pickle or ANYTHING, just a bit too pricy.  For me, a side free 8 dollar sandwich should be something I'd be happy to eat again, or at least big enough for 2 people to share for a light meal, this fell short of those marks. I also grabbed the cauliflower, which wasn't bad, but like the sandwich, on the steeper end at 4 dollars for what you got, and nothing I'd come back for.  So, generally, pretty meh."},
           {description: "Fried Cauliflower is amazing! Tomato, Mozarella sandwich was also great.  The mozzarella was so fresh and the focaccia bread was right out of the oven. I know this because they asked us to wait for it to cool."},
           {description: "Tried out the pepperoni pizza today. Flavor was awesome, its obvious that everything is home made and high quality. They get the crust perfectly crispy. You can't beat the price either we split an 11 inch for lunch for 9$. One of the top pizzas in Boston."},
           {description: "We actually visited the food truck at Assembly row during opening weekend. Most of the specialty pizzas were about $ 9.00 for an 11 inch size.  We opted for the Buffalo chicken with oven roasted chicken, mozzarella, Romano, Gorgonzola cheese topped with buffalo sauce. I'm not sure if I was just starving or not but the pizza was wonderful.  It was soooo good! Everything tasted fresh and the crust was perfect; it was soft, crispy and chewy."},
           {description: "Everything about my chicken pesto pizza was boring.  The cheese had little to no taste, the pesto was a few sprigs of basil plunked down under the cheese, and the chicken was just little crumbles with no seasoning.  I was excited to try this place, but ended up bummed (the opposite of stoked :| ).  I think I'll stick to pizza from an establishment without wheels for now."},
           {description: "Delicious pizza. Today was my second time going to this food truck and both times I was so happy with my pizza. I got the pepperoni pizza again, it was just so good the first time that I had to have it again. I love that it's ground peperoni instead of the sliced peperoni.  The buffalo chicken pizza looks so good. That's what I'll be trying next week and I feel confident that I'll love it."},
           {description: "It's really astounding you can get pizza this delicious from a food truck! I tried the pepperoni and the buffalo chicken and everything was fantastic. The crust was especially delicious - not too crispy, not too chewy. This is the best pizza I've had in Boston!"}]

begin_time = Time.new(2005)
end_time = Time.now

User.pluck(:id).each do |user|
  num = rand(20) + 5
  FoodTruck.pluck(:id).sample(num).each_with_index do |truck, i|
    descriptions = reviews.sample(num)
    rating = rand(5) + 1
    if !Review.exists?(rating: rating, body: descriptions[i][:description], food_truck_id: truck, user_id: user)
      new_review = Review.create!(rating: rating, body: descriptions[i][:description], food_truck_id: truck, user_id: user)
      new_review.created_at = rand(begin_time..end_time)
      new_review.save!
    end
  end
end

User.pluck(:id).each do |user|
  Review.pluck(:id).sample(Review.all.count / (rand(4) + 2)).each do |review|
    rand(10) > 2 ? vote = "up" : vote = "down"
    if !Vote.exists?(user_id: user, review_id: review, vote: vote)
      Vote.create!(user_id: user, review_id: review, vote: vote)
    end
  end
end
