FoodTruck.delete_all
User.delete_all
Review.delete_all
Vote.delete_all

num = 20

num.times do |i|
  User.create({
    first_name: Randgen.first_name(length: rand(7) + 4),
    last_name: Randgen.last_name(length: rand(8) + 5),
    email: "seed#{i+1}@seeds.com",
    password: "seeder123",
    password_confirmation: "seeder123"
  })
end

food_trucks = [{name: "Baja Taco Truck", description: "Features amazing tacos, burritos and tostadas made with Carne Asada, chicken and fish prepared as it is in Baja.", website: "http://bajatacotruck.com/"},
               {name: "Benny's Crepe Cafe", description: "New England's best traveling Crepe Cafe. Named after owner Frank Shear's grandfather Benny, they provide nutritious and fun breakfasts and lunches for business people along Route 128 and in Boston. In addition to their truck they also cater parties and corporate luncheons.", website: "http://www.bennyscrepecafe.com/"},
               {name: "Bon Me", description: "Bon Me is run by Boston-bred husband and wife duo Patrick Lynch and Ali Fong. The business was born in 2010 when the two decided to enter the City of Boston’s Food Truck Contest on whim and surprised themselves by winning. With their win came the opening of the first Bon Me truck in 2011.\n\nThree years and lots of sandwiches, rice bowls, and noodle salads later, Bon Me has expanded to four bright food trucks and a restaurant in Kendall Square. All locations are proudly serving the Boston and Cambridge communities bold, fresh, and fun Vietnamese cuisine.", website: "http://www.bonmetruck.com/"},
               {name: "Boston's Baddest Burger & Sandwich Co.", description: "At Boston’s Baddest Burger, our recipe for success is our combination of great food, great service, and even better prices. From food truck burgers on the go to corporate events and even on-location catering, we’ve got all the ingredients to make Boston’s Baddest Burger Food Truck the best in the city and beyond.\n\nWe use only the freshest ingredients from local sources to bring incredibly good food and reasonable prices right to your door. We get our delicious bread and rolls from Iggy’s, a Cambridge-based bakery. We use all Kenneally meat, locally owned and operated in the Boston area since the 1930s, for fresh never frozen, high-quality meat products. We get our produce fresh every day and stock the best in cheeses (Cabot, and more) and toppings. We even have Boston’s Baddest exclusives like Stella’s Homemade Hots made especially for us and Jalapeno Bacon – we’re the only carrier in New England!\n\nFor amazing burgers, deli sandwiches, soups and anything else you could imagine, Boston’s Baddest Burger has got it covered! Whether you stumble across our truck in the city for lunch or you have our truck come to you at your event (with any menu!), there’s something for everyone at Boston’s Baddest Burger.", website: "http://www.bostonsbaddestburger.com/"},
               {name: "Cameo Macaron", description: "Cameo Macaron is Boston's first French Macaron retailer and Food Truck. We are extremely excited about sharing our favorite piece of France with you!", website: "http://www.cameomacaron.com/"},
               {name: "Captain Marden's Cod Squad", description: "The Cod Squad is serving up Captain Marden's award winning exclusive fresh seafood & organic produce creating a traditional New England experience with a twist!", website: "http://www.cmsfoodtrucks.com/"},
               {name: "Chicken & Rice Guys", description: "After a night out in New York City, we were introduced to the wonder of eating Chicken and Rice outside with our friends. We became instant addicts! (Does this sound familiar?) Since that night, each visit to New York City had to be accompanied by a meal of Chicken and Rice, either from the Halal Guys on 53rd and 6th, the Meatpacking district, or Brooklyn with their famous green sauce.\n\nSo we thought “Why is there no Chicken and Rice in Boston?!” With its popularity and lines down and around the block in New York City, it was obvious that Boston was missing out on something incredible. Plans started to hatch in July 2011 for Beantown to have its very own Chicken and Rice food truck.\n\nSince then, support from our customers has been incredible! In 2 short years, we have expanded to 3 food trucks, a thriving corporate catering business, and hopefully will be opening our first restaurant. As we grow, our goal is to be the next fast casual chain that serves delicious food, provides great service, and gives back to the community.", website: "http://www.cnrguys.com/"},
               {name: "Chubby Chickpea", description: "The Chubby Chickpea is your source for the best Mediterranean food in town.  We have a huge selection of handmade falafels, stuffed grape leaves, rotisserie Shawarma, fresh hummus, baklava and more.  If you want healthy, fast, and fresh, look no further than The Chubby Chickpea!\n\nOur restaurant is based in the historical Massachusetts town of Canton, and is Glatt Kosher under the supervision of the KVH.  You can also find our Kosher (KVH/Vaad) food trucks during lunch hours in Boston on the streets of Back Bay, The Waterfront, and Financial District.  Our Catering department is perfect for your small or large private event.", website: "http://thechubbychickpea.com/"},
               {name: "Compliments", description: "Compliments Food Co was born in Jan 2012 when Kim Crocker and Bobby Maclean bought one way tickets to California. Their mission was to bring back a little white step van to Boston and turn it into a food truck. After a long drive and several months of ordering and installing restaurant equipment a food truck was born. The menu was written and spots acquired, but what would set them apart from the rest? The answer, local farms and fresh food. Take great ingredients and prepare them right in front of you! Everything is made to order with their secret ingredient Pure Love. Stop by the truck and see what makes them so special!", website: "http://complimentsfood.com/"},
               {name: "Cookie Monstah", description: "We are a Boston based food truck serving homemade cookies and ice cream sandwiches made with love and the best ingredients available. We bake cookies throughout Boston.", website: "http://thecookiemonstah.com/"},
               {name: "El Diez Argentenian Grill", description: "Good morning!! We had the truck out on the streets of Somerville yesterday parked outside of a test kitchen where we were refining our recipes for our empanadas and chimichurri. I am very excited about the buzz that this generated as I have gotten many phone calls and likes on this page that has been a bit neglected. We have a rough go-live date for the 3rd week in June as we are still waiting on final approval for our site locations in the City of Boston.", website: "http://www.eldiez.us/"},
               {name: "Evan's NY Style Deli", description: "Evan's Deli career started in the late 1980's, at Michael's Deli in Marblehead, where he studied under the tutelage of Michael Sobelman, and learned the true meaning of what Evan likes to call 'Deli-ology!'\n\nIn 1992, Evan moved to New York, the 'birthplace of deli.' where he continued his deli education at the Stage, Carnage, and Katzes Deli, becoming great friends with the owner of the Stage Deli. It was here in the birthplace of Deli Evan earned his 'PHD in Deli-Ology!!!'\n\nAfter moving back to Massachusetts in 2007, Evan noticed a striking need for a true New-York style Deli in Marblehead. In August of 2007, Evan's Deli opened it's doors on 31 Smith Street, and it has become Evan's goal to bring a true taste of New York to Marblehead, MA.\n\nIn 2014, Evan decided to bring 'Deli-Ology!'' on a Food Truck to Boston. Evan's New-York Style Deli Food Truck is all over Boston serving breakfast, lunch and dinner. The Food Truck menu is a selection of the most popular items on the Deli menu in Marblehead. With fresh deli meat from NY, our Deli & Food Truck are truly bringing New York to Boston!", website: "http://www.evansnewyorkstyledeli.com/"},
               {name: "Frozen Hoagies", description: "Opening on July 4th, 2011, Frozen Hoagies is Boston's original ice cream sandwich truck. Homemade cookies and hand scooped ice cream combine to make the perfect cool treat for those hot summer days. Our cookies are the product of a labor of love and family recipes. Our ice cream is locally sourced from Chilly Cow in Arlington. It is hand made in small batches using only the finest ingredients.", website: "http://frozenhoagies.com/"},
               {name: "Fugu Truck", description: "Fugu Truck is dedicated toward bringing authentic Asian street foods to Boston.  Working with pristine and locally sourced ingredients, Fugu Truck creates seasonal and flavorful Asian dishes that is sure to please all palates.\n\nThe name Fugu was inspired by the fugu fish, a unique and sensational delicacy in Asian cuisine.  The preparation of fugu requires an utmost level of devotion and rigorous training.  While the Fugu Truck will not be serving the fugu fish, it embodies the discipline, dedication, and sophistication we hope to bring to our dishes!", website: "http://www.fugutruck.com/"},
               {name: "Green Bean Mobile Cafe", description: "What if every cup of coffee Americans purchase went towards a good cause? From this thought, Green Bean Mobile Cafe was born.\n\nAt Green Bean Mobile Cafe, you can purchase rich, organic, fair trade coffee knowing that a portion of the proceeds will be donated towards Boston’s green initiatives. To eat, Green Bean Mobile Cafe offers a variety of delicious options – from coffee cake and bagels made by local businesses to Belgium waffle and unique panini sandwiches made onboard the truck.\n\nJust think of the impact that can be made if a small fraction of coffee drinkers switch to Green Bean Mobile Cafe.", website: "http://www.ilovegreenbean.com/"},
               {name: "Latin Spoon", description: "Latin Spoon is now serving up their menu on Boston's streets. What's on that menu? Well, empanadas for starters. Perhaps more intriguing is an item they call a 'Pata-Kone' — a cone-shaped shell of fried plantain stuffed with skirt steak, avocado, cilantro, and cheese. The truck is currently on the city's schedule vending both breakfast and lunch. Stops include Trinity Place and Cleveland Circle.", website: "http://www.thelatinspoon.com/"},
               {name: "Lilian's Smokin' Rack BBQ", description: "We provide high quality barbecue dry rubs to allow family and friends to share in the experience of Texas-style barbecue in the comforts of their own home. All our products are hand-blended in small batches using premium quality ingredients. No artificial flavors, additives, or preservatives are used.", website: "http://www.liliansmokinrackbbq.com/"},
               {name: "M&M Ribs", description: "M & M Ribs food truck in Boston serves BBQ dishes.", website: "http://mandmribs.com/"},
               {name: "Makin' Jamaican", description: "The most authentic taste of Jamaica you'll find in Boston! Jamaican Food Truck!", website: "http://www.makinjamaican.com/"},
               {name: "Mei Mei Street Kitchen", description: "Our award-winning food truck serves creative Chinese-American cuisine made from locally sourced, sustainable ingredients. We pride ourselves on serving humanely raised meat, produce from small farms, and some of the most creatively delicious street food out there. Click around to learn more about us, the three sibling founders, and how we try to run our company. Or get the latest word by following us on Twitter, Facebook and Instagram. We’re even up on Pinterest if you want to peruse photos of our food, farms we love, food truck weddings, and other fun stuff. See you on the streets!", website: "http://meimeiboston.com/"},
               {name: "Momogoose", description: "Long lines everywhere we go, Momogoose is Boston’s first gourmet food truck. In 2011, Momogoose was the winner of the Boston Food Truck Challenge.", website: "http://www.momogoose.com/"},
               {name: "Moyzilla", description: "Our goal is to bring the freshest, most creative Asian street food and dumplings to the streets of Boston and beyond. We specialize in creative takes on the ultimate Asian comfort food, the dumpling! From our staple pork and napa cabbage dumpling to out-of-the-box ideas like our “Moyzilla Style” cheeseburger dumpling we passionately believe the dumpling is the perfect vehicle for yumminess.\n\nOur love for dumplings is only matched by our love of classic and creative takes on all other kinds of Asian comfort Food: Moyzilla skewers with unique sauces, rice/noodle bowls, and inspired sandwiches and noodle soups – all using the freshest ingredients.\n\nWe only hope you enjoy eating our food as much as we enjoy serving you!", website: "http://www.moyzillaboston.com/"},
               {name: "Paris Creperie", description: "La Tour Eiffel - Boston's First Crepe Truck. Check out our full schedule on our website.", website: "http://pariscreperie.com/"},
               {name: "Pennypackers", description: "We are a family run business in the Boston area with 2 food trucks, a catering business, and a brick and mortar restaurant. Our truck and restaurant menu changes daily, featuring specialty soups, salads and sandwiches- the only item that stays on daily is our specialty, Porchetta.\n\nPorchetta is an Italian, skin on roast pork- heavily seasoned, cured and marinated in herbs and garlic. We serve it with a variety of toppings, such as onions agrodolce, marinated broccoli rabe, seasonal mostardas, and lemon juice and arugula.", website: "http://www.pennypackersfinefoods.com/"},
               {name: "Redbones Barbecue", description: "Redbones is a well established, much loved restaurant located in Davis Square - Somerville, Massachusetts. RedBones has become a favorite for many folks over the years, most likely due to its authentic downhome-style Southern food, its unique ambience, and the genuine friendliness of its staff. Redbones also offers 24 fresh microbrews on tap and often hosts local Brew Fests. Catering and delivery are available for private functions. ", website: "http://www.redbones.com/"},
               {name: "Rhythm 'N Wraps", description: "Make your special event extra special with great food and service by Rhythm n' Wraps Vegetarian Catering.  We offer full service catering to the Boston Metro area for events of any size with our large mobile food and beverage truck and all necessary equipment. We are very flexible, and will deliver excellence to any type of event, large or small, customized and tailored to the clients needs.", website: "http://rhythmnwraps.com/"},
               {name: "Roxy's Gourmet Grilled Cheese", description: "We don't make your grandma's grilled cheese. We can if you'd like us to, but if you leave it up to us, we're going to put our own twist on things. We're about taking grilled cheese to the next level by adding ingredients you never really thought possible.", website: "http://www.roxysgrilledcheese.com/"},
               {name: "Savory Food Truck", description: "Our company started in May 1992. Our main focus is Chinese food business. Over the years, we operated several Chinese restaurants. Eventually we decided that Chinese style fast food is our niche. Our food truck provide high quality, convenient and economical Asian meals to our customers. We have more trucks ready to serve our customers, please feel free to contact our management team.", website: "http://www.savoryfoodtruck.com/"},
               {name: "Sheherazad", description: "Brining fresh, local, and boisterous home style Middle Eastern food to a modern world. Straying from the norm!", website: "http://www.sheherazadfood.com/"},
               {name: "Stoked Wood Fired Pizza Co.", description: "We strike a balance between the best pizza available in its birthplace, Naples Italy, and the best coal oven pizzas found in New York and New Haven. We prefer a pizza that is soft and light on the inside with a crispy outer shell. To achieve this we use ancient technology - a wood burning oven - for the superior flavor it imparts.\n\nOur fast 2-3 minute bake time allows us to retain the fresh and vibrant flavors of minimally stressed ingredients while also achieving a crispy crust that has just the right amount of char and character. We use organic flour, a blend of California and Italian organic tomatoes and an artisan pepperoni.\n\nAt Stoked wood fired pizza company we source organic and local produce whenever possible, and our chicken is naturally raised. We use aged mozzarellas like those popular in the New York and New Haven areas, with their crave-inducing salty and buttery dimension. The combination of all of this is 'pizza heaven', a perfected artisan pizza that is the best of all worlds.", website: "http://www.stokedpizzaco.com/"},
               {name: "Sweet Tomatoes Pizza", description: "The Sweet Tomatoes Pizza Truck is available for Catering and we would love to work with you to provide our delicious pizzas and salads on-site at your event. Our truck can cater just about any occasion from a backyard party to a full corporate event or an awesome wedding after-party!", website: "http://sweettomatoespizzatruck.com/"},
               {name: "Taco Party", description: "The best veggie joints I’ve been to are the ones that I can sit across the table from my carnivorous pals and they don’t even bat an eyelash. That’s what this is about. Eating well together. I’m not going to preach to you. To each their own. Everyone is free to put whatever they want down their gullet. I’m just here to offer you something a little different and we’re gonna do it in the most sustainable and eco friendly way possible. I’m also not going to claim any authenticity here. I reserve the right to put anything I damn well please in a tortilla. The menu will mainly have Mexican roots but don’t be surprised if things get weird from time to time. Just like a regular party, a taco party can get a little out of hand too.", website: "http://tacopartytruck.com/"},
               {name: "Tenoch Mexican", description: "Tenoch Mexican brings authentic, affordable, high quality Mexican food to the Boston area. ¡Buen provecho!", website: "http://www.tenochmexican.com/"},
               {name: "The Bacon Truck", description: "The Bacon Truck proudly serves Blackstone St. Smokehouse's thick-cut, applewood smoked bacon. Prepared and smoked right here in South Boston, it's the best bacon around. Next spring we'll be selling it by the pound at our truck for you to take home and cook yourself!", website: "http://www.bostonbacontruck.com/"},
               {name: "The Dining Car", description: "The Dining Car is a mobile food truck and catering company – a kitchen on wheels, serving freshly prepared meals on the streets of Boston. Our sandwiches are made on great breads, and our focaccia is baked right on the truck, continuously throughout the day. Our ever-changing menu features meats and seasonal produce that represent our local agricultural community, with selections inspired by cuisines from all over the world.", website: "http://www.diningcar.net/"},
               {name: "The Pasta Pot", description: "The Pasta Pot is a family owned and operated 'restaurant on wheels' operating mostly in Boston, serving at special events all over New England. We have new twists on all your italian favorites. Our signature dish is our famous Meatball Mac & Cheese! It's to die for!", website: "http://thepastapot.com/"},
               {name: "The Taco Truck", description: "The Taco Truck was born out of an adventurous and extraordinary idea - to bring the authentic Mexican taqueria cuisine that we love so much to the East Coast. With our entrepreneurial spirit and desire to create unique and inspiring brands in tow, we set out to bring this authenticity to the nation in an experimental way: a food truck. In 2009 we launched our very first truck in New Jersey. It turns out we weren’t the only ones craving authentic Mexican tacos, and with a commitment to sustainability we’ve forged ahead. So far we've opened stores, kiosks, carts, and trucks in NY, MA, and NJ - and we're only getting started!", website: "http://thetacotruck.com/"},
               {name: "Uyghur Kitchen", description: "As one can imagine the food of the Uyghurs are largely influenced by the historic exchange of goods in this area, making them mostly traders. Xinjiang’s harsh desert terrain is largely uncultivable, but a system of irrigation introduced by the ancient Uyghurs created “oases,” allowing people in this area to begin cultivating vegetables, wheat and fruit. These oases are famous for producing sweet melons and grapes. However, the feature food of the Uyghurs is the incredible Lamb Kebab, often simply prepared allowing the quality of the meat to shine. Lamb Kebabs roasting over coals and nan, a leavened flatbread cooked in a Tandoor oven, are common street foods for Uyghurs.", website: "http://uyghurkitchen.com/"},
               {name: "Wow Barbecue", description: "Founded on July 1st 2013, Wow Barbecue began serving authentic Chinese Barbecue (food on a stick) on the streets of Boston in a bright red food truck. Along with 10 other partners, Wow Barbecue was founded and currently managed by Babson College MBA graduate Steve Liu. Most recently Wow Barbecue has expanded into two food trucks and opened a brick and mortar restaurant in the city of Malden, MA. Our mission is to introduce this delicious, and totally foreign food to the city of Boston and furthermore to provide a taste of home for all Chinese nationals working and studying in the area.", website: "http://www.wowbarbecue.com/"},
               {name: "Zo Authentic Gyros", description: "A few years back while visiting Greece and sampling some authentic Gyros, we discovered the great taste that was centuries in the making, but not for sale in the Boston Metro area. After being in the restaurant business for years, we knew that authentic Greek cuisine would be embraced by businessmen, tourists and foodies alike. Come discover a new taste and why it’s worth the trip. It’s Zo Good!", website: "http://www.zoboston.com/"}]

food_trucks.each do |info|
  info[:user_id] = User.pluck(:id).sample
  if !FoodTruck.exists?(info)
    FoodTruck.create!(info)
  end
end

